---
- name: Install Redis package
  package:
    name: "{{redis_pkg_name}}"
    state: present
    update_cache: yes

- name: Template of redis.conf
  template:
    src: redis.conf.j2
    dest: "{{redis_dir}}/redis.conf"
    owner: "{{redis_user}}"
    group: root
    mode: 0640
  vars:
    port: "{{redis_port}}"
    bind_ip: "{{redis_bind_ip}}"
    db_dir: "{{redis_db_dir}}"
    pidfile: "{{redis_pidfile}}"
    logfile: "{{redis_logfile}}"
    log_level: "{{redis_log_level}}"
  notify: Restart_redis.service

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of redis.monit
  template:
    src: redis.monit.j2
    dest: "{{monit_includedir}}/redis.monit"
    mode: 0644
  vars:
    pidfile: "{{redis_pidfile}}"
    start_program: '/usr/bin/systemctl start {{redis_pkg_name}}'
    stop_program: '/usr/bin/systemctl stop {{redis_pkg_name}}'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
